/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package do_an_java_new.VIEW.WorkSpaces.StaffWorkSpaces;

import do_an_java_new.BLL.ChiTietHoaDonBLL;
import do_an_java_new.BLL.HangBLL;
import do_an_java_new.BLL.HoaDonBLL;
import do_an_java_new.BLL.KhuyenMaiBLL;
import do_an_java_new.BLL.SanPhamBLL;
import do_an_java_new.DTO.ChiTietHoaDonDTO;
import do_an_java_new.DTO.HoaDonDTO;
import do_an_java_new.DTO.SanPhamDTO;
import do_an_java_new.VIEW.POPUPS.StaffPopUps.BillPopUp;
import do_an_java_new.VIEW.POPUPS.StaffPopUps.ChangeAmountPopUp;
import do_an_java_new.VIEW.POPUPS.StaffPopUps.TimHangPopUp;
import do_an_java_new.VIEW.POPUPS.StaffPopUps.TimKhuyenMai;
import do_an_java_new.VIEW.POPUPS.StaffPopUps.TimKiemKhachHangPopUp;
import do_an_java_new.VIEW.POPUPS.StaffPopUps.Wrapper;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ASUS-PC
 */
public class LapHoaDonPanel extends javax.swing.JPanel {
    /**
     * Creates new form LapHoaDonPanel
     */    
    private String maNhanVien;
    private ArrayList<ChiTietHoaDonDTO> dsChiTietHoaDon = new ArrayList<>();
    private int tongTien;
    private int giamGia;
    
    public LapHoaDonPanel(String maNhanVien) {
        initComponents();
        this.maNhanVien = maNhanVien;
        
        renderTable();
    }
    
    private void renderTable() {
        DefaultTableModel model = (DefaultTableModel) tbCTHD.getModel();
        model.setRowCount(0);
        
        try {
            for (ChiTietHoaDonDTO cthd: dsChiTietHoaDon) {
                model.addRow(new Object[]{
                    cthd.getMaHang(),
                    HangBLL.timHang(cthd.getMaHang()).getTenSP(),
                    cthd.getSoLuong(),
                    cthd.getDonGia(),
                    cthd.getDonGia()*cthd.getSoLuong()
                });
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
        
        int tienGiam = tongTien*giamGia/100;
        
        txtTienGiam.setText(String.format("%d", tienGiam));
        txtTongTien.setText(String.format("%d", tongTien - tienGiam));
    }
    
    private void clearData() {
        dsChiTietHoaDon.clear();
        tongTien = 0;
        txtMaKhachHang.setText("");
        txtMaKM.setText("");
        renderTable();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JTextField();
        btnSearchCustomer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCTHD = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        btnXoaKM = new javax.swing.JButton();
        btnTimKM = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtTienGiam = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnChangeAmount = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 173, 59));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã khách hàng");
        jPanel8.add(jLabel2);

        txtMaKhachHang.setEditable(false);
        txtMaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaKhachHang.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel8.add(txtMaKhachHang);

        btnSearchCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearchCustomer.setText("...");
        btnSearchCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchCustomerMouseClicked(evt);
            }
        });
        jPanel8.add(btnSearchCustomer);

        jPanel1.add(jPanel8);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        tbCTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hàng", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tbCTHD);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tổng tiền:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel5.add(jLabel1, gridBagConstraints);

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTongTien.setPreferredSize(new java.awt.Dimension(100, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel5.add(txtTongTien, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Mã khuyến mãi:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel5.add(jLabel3, gridBagConstraints);

        txtMaKM.setEditable(false);
        txtMaKM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaKM.setPreferredSize(new java.awt.Dimension(100, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel5.add(txtMaKM, gridBagConstraints);

        btnXoaKM.setText("X");
        btnXoaKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaKMMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel5.add(btnXoaKM, gridBagConstraints);

        btnTimKM.setText("...");
        btnTimKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimKMMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel5.add(btnTimKM, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Giảm:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel5.add(jLabel4, gridBagConstraints);

        txtTienGiam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTienGiam.setPreferredSize(new java.awt.Dimension(100, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel5.add(txtTienGiam, gridBagConstraints);

        jPanel4.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel6.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/do_an_java_new/Resources/Add.png"))); // NOI18N
        btnInsert.setText("Thêm sản phẩm  ");
        btnInsert.setRolloverEnabled(false);
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertMouseClicked(evt);
            }
        });
        jPanel7.add(btnInsert);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/do_an_java_new/Resources/Delete.png"))); // NOI18N
        btnDelete.setText("Xoá sản phẩm     ");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        jPanel7.add(btnDelete);

        btnChangeAmount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/do_an_java_new/Resources/Pencil.png"))); // NOI18N
        btnChangeAmount.setText("Sửa số lượng       ");
        btnChangeAmount.setName(""); // NOI18N
        btnChangeAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangeAmountMouseClicked(evt);
            }
        });
        jPanel7.add(btnChangeAmount);

        jPanel2.add(jPanel7, java.awt.BorderLayout.EAST);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCancel.setBackground(new java.awt.Color(255, 153, 153));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setText("Huỷ hoá đơn");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        jPanel3.add(btnCancel);

        btnSubmit.setBackground(new java.awt.Color(153, 255, 153));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSubmit.setText("Hoàn tất hoá đơn");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });
        jPanel3.add(btnSubmit);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchCustomerMouseClicked
        TimKiemKhachHangPopUp popUp = new TimKiemKhachHangPopUp(txtMaKhachHang);
        popUp.setVisible(true);
    }//GEN-LAST:event_btnSearchCustomerMouseClicked

    private void btnInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseClicked
        ChiTietHoaDonDTO cthd = new ChiTietHoaDonDTO();
        TimHangPopUp popUp = new TimHangPopUp(cthd);
        popUp.setVisible(true);
        
        popUp.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                super.windowClosed(e);
                if (cthd.getMaHang() == null)
                    return;
                for (ChiTietHoaDonDTO sub: dsChiTietHoaDon) 
                    if (sub.getMaHang().equals(cthd.getMaHang())) {
                        JOptionPane.showMessageDialog(null, "Hàng đã được thêm!", "", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                dsChiTietHoaDon.add(cthd);
                tongTien += cthd.getDonGia() * cthd.getSoLuong();
                renderTable();
            }
        });
    }//GEN-LAST:event_btnInsertMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbCTHD.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Hãy chọn sản phẩm cần xoá");
            return;
        }
        
        for (int i = 0 ; i < dsChiTietHoaDon.size() ; i++) 
            if (dsChiTietHoaDon.get(i).getMaHang().equals(tbCTHD.getValueAt(selectedRow, 0))){
                tongTien -= dsChiTietHoaDon.get(i).getDonGia()*dsChiTietHoaDon.get(i).getSoLuong();
                dsChiTietHoaDon.remove(i);
                break;
            }
        
        renderTable();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        clearData();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnChangeAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeAmountMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbCTHD.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Hãy chọn sản phẩm cần sửa");
            return;
        }
        
        for (int i = 0 ; i < dsChiTietHoaDon.size() ; i++) 
            if (dsChiTietHoaDon.get(i).getMaHang().equals(tbCTHD.getValueAt(selectedRow, 0))) {
                ChiTietHoaDonDTO ct = dsChiTietHoaDon.get(i);
                tongTien -= ct.getDonGia() * ct.getSoLuong();
                
                Wrapper tmp = new Wrapper(ct.getSoLuong());
                ChangeAmountPopUp popUp = new ChangeAmountPopUp(tmp); 
                
                popUp.setVisible(true);
                popUp.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent e) {
                        super.windowClosed(e); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                        ct.setSoLuong(tmp.getData());
                        tongTien += ct.getDonGia() * ct.getSoLuong();  
                        renderTable();
                    }
                });
                break;
            }
    }//GEN-LAST:event_btnChangeAmountMouseClicked

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        // TODO add your handling code here:
        if (dsChiTietHoaDon.size() < 1) {
            JOptionPane.showMessageDialog(null, "Danh sách chi tiết hoá đơn đang bị trống, không thể tạo hoá đơn");
            return;
        }
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("yymmddhhmmss");
        String 
                maHD = String.format("HD.%s.%s", maNhanVien, LocalDateTime.now().format(timeFormatter)),
                maKH = txtMaKhachHang.getText().trim();
        
        HoaDonDTO hoaDon = new HoaDonDTO(maHD, maKH, maNhanVien, tongTien, Date.valueOf(LocalDate.now()), txtMaKM.getText() == "" ? null : txtMaKM.getText());
        
        for (ChiTietHoaDonDTO ct: dsChiTietHoaDon) {
            ct.setMaHD(maHD);
        }
        
        try {
            HoaDonBLL.themHoaDon(hoaDon);
            
            for (ChiTietHoaDonDTO ct: dsChiTietHoaDon) 
                HangBLL.updateSoLuong(ct.getMaHang(), -ct.getSoLuong());
            
            KhuyenMaiBLL.updateSoLuong(hoaDon.getMaKM(), -1);
            
            ChiTietHoaDonBLL.themCTHD(dsChiTietHoaDon);
            
            int tienGiam = tongTien*giamGia/100;
            new BillPopUp(hoaDon, tienGiam).setVisible(true);
            
            clearData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Có lỗi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitMouseClicked

    private void btnXoaKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaKMMouseClicked
        // TODO add your handling code here:
        txtMaKM.setText("");
        giamGia = 0;
        renderTable();
    }//GEN-LAST:event_btnXoaKMMouseClicked

    private void btnTimKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimKMMouseClicked
        // TODO add your handling code here:
        ArrayList<String> products = new ArrayList<>();
        try {
            for (ChiTietHoaDonDTO cthd: dsChiTietHoaDon) 
                products.add(HangBLL.timHang(cthd.getMaHang()).getMaSP());
            
            TimKhuyenMai popUp = new TimKhuyenMai(txtMaKM, products);
            popUp.setVisible(true);
            
            popUp.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    super.windowClosed(e); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
                    if (txtMaKM.getText().equals(""))
                        return;
                    try {
                        giamGia = KhuyenMaiBLL.timKhuyenMai(txtMaKM.getText().trim()).getGiaTri();
                        renderTable();
                    } catch (SQLException ex) {
                        Logger.getLogger(LapHoaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTimKMMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChangeAmount;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearchCustomer;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnTimKM;
    private javax.swing.JButton btnXoaKM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCTHD;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtMaKhachHang;
    private javax.swing.JTextField txtTienGiam;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
