/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package do_an_java_new.VIEW.WorkSpaces.StaffWorkSpaces;

/**
 *
 * @author ASUS-PC
 */
public class LichSuPanel extends javax.swing.JPanel {

    /**
     * Creates new form LichSuPanel
     */
    private String nhanVien;
    
    public LichSuPanel(String nhanVien) {
        initComponents();
        this.nhanVien = nhanVien;
        
        renderWorkSpace();
    }

    private void renderWorkSpace() {
        hoaDon.add(new LichSuHDPanel(nhanVien));
        phieuNhap.add(new LichSuNHPanel(nhanVien));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        hoaDon = new javax.swing.JPanel();
        phieuNhap = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        hoaDon.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Hoá đơn", hoaDon);

        phieuNhap.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Phiếu nhập", phieuNhap);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hoaDon;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel phieuNhap;
    // End of variables declaration//GEN-END:variables
}
