/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package do_an_java_new.VIEW.WorkSpaces.StaffWorkSpaces;

import do_an_java_new.BLL.ChiTietNhapHangBLL;
import do_an_java_new.BLL.HangBLL;
import do_an_java_new.BLL.NhapHangBLL;
import do_an_java_new.DTO.ChiTietNhapHangDTO;
import do_an_java_new.DTO.HangDTO;
import do_an_java_new.DTO.NhapHangDTO;
import do_an_java_new.VIEW.POPUPS.StaffPopUps.ChangeAmountPopUp;
import do_an_java_new.VIEW.POPUPS.StaffPopUps.TimNhaCungCapPopUp;
import do_an_java_new.VIEW.POPUPS.StaffPopUps.TimSanPhamPopUp;
import do_an_java_new.VIEW.POPUPS.StaffPopUps.Wrapper;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.time.LocalDate;

/**
 *
 * @author ASUS-PC
 */
public class NhapHangPanel extends javax.swing.JPanel {
    /**
     * Creates new form LapHoaDonPanel
     */    
    private String maNhanVien;
    private ArrayList<ChiTietNhapHangDTO> dsChiTietNhapHang = new ArrayList<>();
    private ArrayList<HangDTO> dsHang = new ArrayList<>();
    private int tongTien;
    
    public NhapHangPanel(String maNhanVien) {
        initComponents();
        this.maNhanVien = maNhanVien;
        
        renderTable();
    }
    
    private void renderTable() {
        DefaultTableModel model = (DefaultTableModel) tbCTNH.getModel();
        model.setRowCount(0);
        
        for (ChiTietNhapHangDTO ctnh: dsChiTietNhapHang) {
            HangDTO hang = null;
            for (HangDTO sub: dsHang)
                if (sub.getMaHang().equals(ctnh.getMaHang())) {
                    hang = sub;
                    break;
                }

            model.addRow(new Object[]{
                hang.getMaSP(),
                hang.getTenSP(),
                ctnh.getSoLuong(),
                ctnh.getDonGia(),
                ctnh.getDonGia()*ctnh.getSoLuong()
            });
        }
        
        txtTongTien.setText(String.format("%d", tongTien));
    }
    
    private void clearData() {
        dsChiTietNhapHang.clear();
        dsHang.clear();
        tongTien = 0;
        txtMaNCC.setText("");
        renderTable();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaNCC = new javax.swing.JTextField();
        btnSearchSuplier = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCTNH = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnChangeAmount = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 173, 59));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Mã nhà cung cấp");
        jPanel8.add(jLabel2);

        txtMaNCC.setEditable(false);
        txtMaNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaNCC.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel8.add(txtMaNCC);

        btnSearchSuplier.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSearchSuplier.setText("...");
        btnSearchSuplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchSuplierMouseClicked(evt);
            }
        });
        jPanel8.add(btnSearchSuplier);

        jPanel1.add(jPanel8);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        tbCTNH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tbCTNH);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tổng tiền:");
        jPanel5.add(jLabel1);

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTongTien.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel5.add(txtTongTien);

        jPanel4.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel6.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/do_an_java_new/Resources/Add.png"))); // NOI18N
        btnInsert.setText("Thêm sản phẩm");
        btnInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertMouseClicked(evt);
            }
        });
        jPanel7.add(btnInsert);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/do_an_java_new/Resources/Delete.png"))); // NOI18N
        btnDelete.setText("Xoá sản phẩm  ");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        jPanel7.add(btnDelete);

        btnChangeAmount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/do_an_java_new/Resources/Pencil.png"))); // NOI18N
        btnChangeAmount.setText("Sửa số lượng    ");
        btnChangeAmount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangeAmountMouseClicked(evt);
            }
        });
        jPanel7.add(btnChangeAmount);

        jPanel2.add(jPanel7, java.awt.BorderLayout.EAST);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCancel.setBackground(new java.awt.Color(255, 153, 153));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setText("Huỷ phiếu nhập");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        jPanel3.add(btnCancel);

        btnSubmit.setBackground(new java.awt.Color(153, 255, 153));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSubmit.setText("Hoàn tất phiếu nhập");
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmitMouseClicked(evt);
            }
        });
        jPanel3.add(btnSubmit);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchSuplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchSuplierMouseClicked
        TimNhaCungCapPopUp popUp = new TimNhaCungCapPopUp(txtMaNCC);
        popUp.setVisible(true);
    }//GEN-LAST:event_btnSearchSuplierMouseClicked

    private void btnInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertMouseClicked
        ChiTietNhapHangDTO ctnh = new ChiTietNhapHangDTO() ;
        HangDTO hang = new HangDTO() ;
        
        TimSanPhamPopUp popUp = new TimSanPhamPopUp(ctnh, hang);
        popUp.setVisible(true);
        
        popUp.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                super.windowClosed(e);
                if (hang.getMaHang() == null)
                    return;
                for (HangDTO sub: dsHang) 
                    if (sub.getMaSP().equals(hang.getMaSP())) {
                        JOptionPane.showMessageDialog(null, "Sản phẩm đã được thêm!", "", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                
                dsChiTietNhapHang.add(ctnh);
                
                dsHang.add(hang);
                tongTien += ctnh.getDonGia() * ctnh.getSoLuong();
                renderTable();
            }
        });
    }//GEN-LAST:event_btnInsertMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbCTNH.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Hãy chọn sản phẩm cần xoá");
            return;
        }
        
        HangDTO hang = null;
        
        for (int i = 0 ; i < dsHang.size() ; i++) 
            if (dsHang.get(i).getMaSP().equals(tbCTNH.getValueAt(selectedRow, 0))) {
                hang = dsHang.get(i);
                dsHang.remove(i);
                break;
            }
        
        for (int i = 0 ; i < dsChiTietNhapHang.size() ; i++) {
            ChiTietNhapHangDTO ct = dsChiTietNhapHang.get(i);
            if (ct.getMaHang().equals(hang.getMaHang())) {
                tongTien -= ct.getDonGia() * ct.getSoLuong();
                dsChiTietNhapHang.remove(i);
            }
        }
        renderTable();
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        clearData();
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnChangeAmountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeAmountMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbCTNH.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Hãy chọn sản phẩm cần sửa");
            return;
        }
        
        for (HangDTO sub: dsHang) 
            if (sub.getMaSP().equals(tbCTNH.getValueAt(selectedRow, 0))) {
                HangDTO hang = sub;
                
                Wrapper tmp = new Wrapper(hang.getSoLuong());
                ChangeAmountPopUp popUp = new ChangeAmountPopUp(tmp);
                
                popUp.setVisible(true);
                popUp.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosed(WindowEvent e) {
                        super.windowClosed(e); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody

                        hang.setSoLuong(tmp.getData());
                        
                        for (ChiTietNhapHangDTO ct: dsChiTietNhapHang)
                            if (ct.getMaHang().equals(hang.getMaHang())) {
                                tongTien -= ct.getDonGia() * ct.getSoLuong();
                                ct.setSoLuong(tmp.getData());
                                tongTien += ct.getDonGia() * ct.getSoLuong();
                            }
                    renderTable();
                    }
                });
                break;
            }
        
    }//GEN-LAST:event_btnChangeAmountMouseClicked

    private void btnSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseClicked
        if (dsChiTietNhapHang.size() < 1 || dsHang.size() < 1) {
            JOptionPane.showMessageDialog(null, "Danh sách chi tiết nhập hàng đang bị trống, không thể tạo phiếu nhập");
            return;
        }
        DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("yymmddhhmmss");
        String 
                maNH = String.format("NH.%s.%s", maNhanVien, LocalDateTime.now().format(timeFormatter)),
                maNCC = txtMaNCC.getText().trim();
        
        NhapHangDTO nh = new NhapHangDTO(maNH, maNCC, maNhanVien, tongTien, Date.valueOf(LocalDate.now()));
        for (ChiTietNhapHangDTO ct: dsChiTietNhapHang) 
            ct.setMaPhieu(maNH);
        
        try {
            
            HangBLL.themHang(dsHang);
            
            NhapHangBLL.themNhapHang(nh);
            ChiTietNhapHangBLL.themCTNH(dsChiTietNhapHang);
            
            JOptionPane.showMessageDialog(null, "Lập phiếu nhập hàng thành công");
            
            clearData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Có lỗi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChangeAmount;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSearchSuplier;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCTNH;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
