/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package do_an_java_new.VIEW.WorkSpaces.StaffWorkSpaces;

import do_an_java_new.BLL.KhachHangBLL;
import do_an_java_new.BLL.TinhThanhBLL;
import do_an_java_new.DTO.KhachHangDTO;
import java.sql.Date;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS-PC
 */
public class ThemKhachhangPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThemKhachhangPanel
     */
    public ThemKhachhangPanel() {
        initComponents();
        txtNgaySinh.setDate(Date.valueOf(LocalDate.now()));
        initComboboxs();
    }
    
    private void clearData() {
        initComponents();
        txtNgaySinh.setDate(Date.valueOf(LocalDate.now()));
        initComboboxs();
    }
    
    private void initComboboxs() {
        DefaultComboBoxModel<String> comboBoxModel = (DefaultComboBoxModel<String>) cbbTinh.getModel();
        comboBoxModel.removeAllElements();
        
        try{
            for (String tinh: TinhThanhBLL.getDanhSachTinh()) {
                comboBoxModel.addElement(tinh);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    
    public void xacNhan() {
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yymmddhhmmss");
            String maKH = String.format("KH.%s", LocalDateTime.now().format(formatter));
            String ho = txtHo3.getText().trim();
            String tenLot = txtTenLot.getText().trim();
            String ten = txtTen.getText().trim();
            String phai = nam.isSelected() ? "nam" : nu.isSelected() ? "nu" : null;
            Date ngaySinh = new Date(txtNgaySinh.getDate().getTime());
            String sdt = txtSDT.getText().trim();
            String tinh = (String) cbbTinh.getSelectedItem();
            String diaChi = txtDiaChi.getText().trim();
            Date ngayThamGia = Date.valueOf(LocalDate.now());
            int diem = 0;
            String trangThai = "active";

            KhachHangDTO khachHang = new KhachHangDTO(maKH, ho, tenLot, ten, phai, ngaySinh, sdt, tinh, diaChi, ngayThamGia, diem, trangThai);
            
            KhachHangBLL.themKhacHang(khachHang);
           
            JOptionPane.showMessageDialog(null, "Thêm khách hàng thành công");
            clearData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupPhai = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        headline = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtHo3 = new javax.swing.JTextField();
        txtTenLot = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        nam = new javax.swing.JRadioButton();
        nu = new javax.swing.JRadioButton();
        cbbTinh = new javax.swing.JComboBox<>();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        btnHuy = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 173, 59));

        headline.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headline.setForeground(new java.awt.Color(204, 255, 204));
        headline.setText("Thêm khách hàng");
        jPanel1.add(headline);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        java.awt.GridBagLayout jPanel5Layout = new java.awt.GridBagLayout();
        jPanel5Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel5Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel5.setLayout(jPanel5Layout);

        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setText("Ho");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel5.add(jLabel30, gridBagConstraints);

        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setText("Ten lot");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel5.add(jLabel31, gridBagConstraints);

        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setText("Ten");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        jPanel5.add(jLabel32, gridBagConstraints);

        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setText("Phai");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        jPanel5.add(jLabel33, gridBagConstraints);

        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setText("Ngay sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        jPanel5.add(jLabel34, gridBagConstraints);

        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setText("SDT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        jPanel5.add(jLabel35, gridBagConstraints);

        jLabel36.setForeground(new java.awt.Color(51, 51, 51));
        jLabel36.setText("Tinh thanh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 28;
        jPanel5.add(jLabel36, gridBagConstraints);

        jLabel37.setForeground(new java.awt.Color(51, 51, 51));
        jLabel37.setText("Dia chi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 32;
        jPanel5.add(jLabel37, gridBagConstraints);

        txtHo3.setMinimumSize(new java.awt.Dimension(130, 26));
        txtHo3.setName(""); // NOI18N
        txtHo3.setPreferredSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        jPanel5.add(txtHo3, gridBagConstraints);

        txtTenLot.setMinimumSize(new java.awt.Dimension(130, 26));
        txtTenLot.setName(""); // NOI18N
        txtTenLot.setPreferredSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        jPanel5.add(txtTenLot, gridBagConstraints);

        txtTen.setMinimumSize(new java.awt.Dimension(130, 26));
        txtTen.setName(""); // NOI18N
        txtTen.setPreferredSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        jPanel5.add(txtTen, gridBagConstraints);

        txtSDT.setMinimumSize(new java.awt.Dimension(130, 26));
        txtSDT.setName(""); // NOI18N
        txtSDT.setPreferredSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 5;
        jPanel5.add(txtSDT, gridBagConstraints);

        txtDiaChi.setMinimumSize(new java.awt.Dimension(130, 26));
        txtDiaChi.setName(""); // NOI18N
        txtDiaChi.setPreferredSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 32;
        gridBagConstraints.gridwidth = 5;
        jPanel5.add(txtDiaChi, gridBagConstraints);

        buttonGroupPhai.add(nam);
        nam.setForeground(new java.awt.Color(51, 51, 51));
        nam.setText("nam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        jPanel5.add(nam, gridBagConstraints);

        buttonGroupPhai.add(nu);
        nu.setForeground(new java.awt.Color(51, 51, 51));
        nu.setText("nu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 16;
        jPanel5.add(nu, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.gridwidth = 5;
        jPanel5.add(cbbTinh, gridBagConstraints);

        txtNgaySinh.setMinSelectableDate(new java.util.Date(-62135791108000L));
        txtNgaySinh.setMinimumSize(new java.awt.Dimension(140, 26));
        txtNgaySinh.setPreferredSize(new java.awt.Dimension(120, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.gridwidth = 5;
        jPanel5.add(txtNgaySinh, gridBagConstraints);

        add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnHuy.setBackground(new java.awt.Color(255, 153, 153));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(0, 0, 0));
        btnHuy.setText("Huỷ");
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyMouseClicked(evt);
            }
        });
        jPanel6.add(btnHuy);

        btnXacNhan.setBackground(new java.awt.Color(153, 255, 153));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXacNhanMouseClicked(evt);
            }
        });
        jPanel6.add(btnXacNhan);

        add(jPanel6, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanMouseClicked
        // TODO add your handling code here:
        xacNhan();
    }//GEN-LAST:event_btnXacNhanMouseClicked

    private void btnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseClicked
        // TODO add your handling code here:
        clearData();
    }//GEN-LAST:event_btnHuyMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.ButtonGroup buttonGroupPhai;
    protected javax.swing.JComboBox<String> cbbTinh;
    private javax.swing.JLabel headline;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    protected javax.swing.JRadioButton nam;
    protected javax.swing.JRadioButton nu;
    protected javax.swing.JTextField txtDiaChi;
    protected javax.swing.JTextField txtHo3;
    protected com.toedter.calendar.JDateChooser txtNgaySinh;
    protected javax.swing.JTextField txtSDT;
    protected javax.swing.JTextField txtTen;
    protected javax.swing.JTextField txtTenLot;
    // End of variables declaration//GEN-END:variables
}
