/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package do_an_java_new.VIEW.WorkSpaces.StaffWorkSpaces;

import do_an_java_new.BLL.NhanVienBLL;
import do_an_java_new.BLL.TinhThanhBLL;
import do_an_java_new.DTO.NhanVienDTO;
import do_an_java_new.VIEW.POPUPS.StaffPopUps.ChangePasswordPopUp;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.sql.Date;

/**
 *
 * @author ASUS-PC
 */
public class ThongTinNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinNhanVien
     */
    private NhanVienDTO nv;
    
    public ThongTinNhanVien() {
        initComponents();
    }
    
    public ThongTinNhanVien(NhanVienDTO nv) {
        initComponents();
        initComboboxs();

        this.nv = nv;
        
        txtHo.setText(nv.getHo());
        txtTenLot.setText(nv.getTenLot());
        txtTen.setText(nv.getTen());
        txtNgaySinh.setDate(nv.getNgaysinh());
        txtSDT.setText(nv.getSdt());
        cbbTinh.setSelectedItem(nv.getTinh());
        txtDiaChi.setText(nv.getDiachi());

        if ("Nam".equalsIgnoreCase(nv.getPhai())) 
            nam.setSelected(true);
        else 
            nu.setSelected(true);
    }       
    private void initComboboxs() {
        DefaultComboBoxModel<String> comboBoxModel = (DefaultComboBoxModel<String>) cbbTinh.getModel();
        
        try{
            for (String tinh: TinhThanhBLL.getDanhSachTinh()) {
                comboBoxModel.addElement(tinh);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void refresh() {
        initComponents();
        initComboboxs();

        txtHo.setText(nv.getHo());
        txtTenLot.setText(nv.getTenLot());
        txtTen.setText(nv.getTen());
        txtNgaySinh.setDate(nv.getNgaysinh());
        txtSDT.setText(nv.getSdt());
        cbbTinh.setSelectedItem(nv.getTinh());
        txtDiaChi.setText(nv.getDiachi());

        if ("nam".equalsIgnoreCase(nv.getPhai())) 
            nam.setSelected(true);
        else 
            nu.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnHuy = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        txtTenLot = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        nam = new javax.swing.JRadioButton();
        nu = new javax.swing.JRadioButton();
        cbbTinh = new javax.swing.JComboBox<>();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        txtChangePassWord = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        headline = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(232, 245, 233));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 20, 0, 20, 0};
        jPanel2Layout.rowHeights = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        jPanel2.setLayout(jPanel2Layout);

        btnHuy.setBackground(new java.awt.Color(255, 153, 153));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(0, 0, 0));
        btnHuy.setText("Reset");
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        jPanel2.add(btnHuy, gridBagConstraints);

        btnXacNhan.setBackground(new java.awt.Color(153, 255, 153));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXacNhan.setText("đổi thông tin");
        btnXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXacNhanMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        jPanel2.add(btnXacNhan, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Ho");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Ten lot");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Ten");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Phai");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Ngay sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("SDT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Tinh thanh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        jPanel2.add(jLabel9, gridBagConstraints);

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Dia chi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        jPanel2.add(jLabel10, gridBagConstraints);

        txtHo.setMinimumSize(new java.awt.Dimension(130, 26));
        txtHo.setName(""); // NOI18N
        txtHo.setPreferredSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(txtHo, gridBagConstraints);

        txtTenLot.setMinimumSize(new java.awt.Dimension(130, 26));
        txtTenLot.setName(""); // NOI18N
        txtTenLot.setPreferredSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(txtTenLot, gridBagConstraints);

        txtTen.setMinimumSize(new java.awt.Dimension(130, 26));
        txtTen.setName(""); // NOI18N
        txtTen.setPreferredSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(txtTen, gridBagConstraints);

        txtSDT.setMinimumSize(new java.awt.Dimension(130, 26));
        txtSDT.setName(""); // NOI18N
        txtSDT.setPreferredSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(txtSDT, gridBagConstraints);

        txtDiaChi.setMinimumSize(new java.awt.Dimension(130, 26));
        txtDiaChi.setName(""); // NOI18N
        txtDiaChi.setPreferredSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(txtDiaChi, gridBagConstraints);

        buttonGroup1.add(nam);
        nam.setForeground(new java.awt.Color(51, 51, 51));
        nam.setText("nam");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanel2.add(nam, gridBagConstraints);

        buttonGroup1.add(nu);
        nu.setForeground(new java.awt.Color(51, 51, 51));
        nu.setText("nu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        jPanel2.add(nu, gridBagConstraints);

        cbbTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(cbbTinh, gridBagConstraints);

        txtNgaySinh.setPreferredSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(txtNgaySinh, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(232, 245, 233));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        txtChangePassWord.setBackground(new java.awt.Color(153, 255, 153));
        txtChangePassWord.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtChangePassWord.setText("đổi mật khẩu");
        txtChangePassWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtChangePassWordMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel4.add(txtChangePassWord, gridBagConstraints);

        add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        headline.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headline.setForeground(new java.awt.Color(46, 125, 50));
        headline.setText("Thông tin nhân viên");
        jPanel1.add(headline);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanMouseClicked
        // TODO add your handling code here:
        String ho = txtHo.getText().trim();
        String tenLot = txtTenLot.getText().trim();
        String ten = txtTen.getText().trim();
        Date ngaySinh = new Date(txtNgaySinh.getDate().getTime());
        String sdt = txtSDT.getText().trim();
        String tinh = cbbTinh.getSelectedItem().toString();
        String diaChi = txtDiaChi.getText().trim();

        String phai = nam.isSelected() ? "nam" : nu.isSelected() ? "nu" : null;
        
        NhanVienDTO nhanVien = new NhanVienDTO(nv.getMaNV(), ho, tenLot, ten, phai, ngaySinh, sdt, tinh, diaChi, nv.getLuong(), nv.getChucVu(), nv.getTrangthai());
        try {
            NhanVienBLL.suaNhanVien(nhanVien);
            
            JOptionPane.showMessageDialog(null, "Sửa thông tin thành công");
            this.nv = nhanVien;
            refresh();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_btnXacNhanMouseClicked

    private void btnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseClicked
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_btnHuyMouseClicked

    private void txtChangePassWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtChangePassWordMouseClicked
        // TODO add your handling code here:
        new ChangePasswordPopUp(nv.getMaNV()).setVisible(true);
    }//GEN-LAST:event_txtChangePassWordMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.ButtonGroup buttonGroup1;
    protected javax.swing.JComboBox<String> cbbTinh;
    private javax.swing.JLabel headline;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    protected javax.swing.JRadioButton nam;
    protected javax.swing.JRadioButton nu;
    private javax.swing.JButton txtChangePassWord;
    protected javax.swing.JTextField txtDiaChi;
    protected javax.swing.JTextField txtHo;
    protected com.toedter.calendar.JDateChooser txtNgaySinh;
    protected javax.swing.JTextField txtSDT;
    protected javax.swing.JTextField txtTen;
    protected javax.swing.JTextField txtTenLot;
    // End of variables declaration//GEN-END:variables
}
