/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package do_an_java_new.VIEW.POPUPS.AdminPopUps;

import do_an_java_new.BLL.KhuyenMaiBLL;
import do_an_java_new.BLL.SanPhamBLL;
import do_an_java_new.DTO.KhuyenMaiDTO;
import do_an_java_new.DTO.SanPhamDTO;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS-PC
 */
public class KhuyenMaiPopUp extends javax.swing.JFrame {

    /**
     * Creates new form NhanVienPopUp
     */    
    public KhuyenMaiPopUp() {
        initComponents();
        
        txtNgayBD.setDate(Date.valueOf(LocalDate.now()));
        txtNgayKT.setDate(Date.valueOf(LocalDate.now()));
        lbTrangThai.setVisible(false);
        active.setVisible(false);
        inactive.setVisible(false);
    }
   
    public void setLabel(String labelString) {
        headline.setText(labelString);
    }
    
    private void xacNhan() {
        try {
            String maKM = txtID.getText().trim();
            String tenKM = txtTen.getText().trim();
            String noiDung = txtNoiDung.getText().trim();
            String maSP = txtMaSP.getText().trim();
            Date ngayBD = new Date(txtNgayBD.getDate().getTime());
            Date ngayKT = new Date(txtNgayKT.getDate().getTime());
            int giaTri = (Integer) spnGiaTri.getValue();
            int soLuong = (Integer) spnSoLuong.getValue();
            String trangThai = "active";
            
            if (maSP.isBlank())
                maSP = null;
            else {
                boolean tmp = false;
                for (SanPhamDTO sp: SanPhamBLL.getDanhSachSanPham(0, 0, "")) 
                    if (sp.getMaSP().equals(maSP)) {
                        tmp = true;
                        break;
                    }
                
                if (!tmp)
                    throw new Exception("Mã sản phẩm không tồn tại");
            }
            
            if (ngayBD.compareTo(ngayKT) >= 0)
                JOptionPane.showMessageDialog(null, "Thời gian áp dụng không hợp lệ");

            KhuyenMaiDTO khuyenMai = new KhuyenMaiDTO(
                maKM, tenKM, noiDung, maSP, ngayBD, ngayKT, giaTri, soLuong, trangThai
            );

            KhuyenMaiBLL.themKhuyenMai(khuyenMai);
            
            dispose();
            JOptionPane.showMessageDialog(null, "Thêm khuyến mãi thành công");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupTrangThai = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        headline = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNoiDung = new javax.swing.JTextField();
        lbTrangThai = new javax.swing.JLabel();
        active = new javax.swing.JRadioButton();
        inactive = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtNgayBD = new com.toedter.calendar.JDateChooser();
        txtNgayKT = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spnGiaTri = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtMaSP = new javax.swing.JTextField();
        btnTimSP = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        spnSoLuong = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        buttonGroupTrangThai.add(active);
        buttonGroupTrangThai.add(inactive);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(430, 550));
        setPreferredSize(new java.awt.Dimension(445, 465));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        headline.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headline.setForeground(new java.awt.Color(46, 125, 50));
        headline.setText("Thêm khuyến mãi");
        jPanel1.add(headline);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel2Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setText("Mã khuyến mãi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel1, gridBagConstraints);

        txtID.setPreferredSize(new java.awt.Dimension(100, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(txtID, gridBagConstraints);

        jLabel2.setText("Tên khuyến mãi");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel2, gridBagConstraints);

        txtTen.setPreferredSize(new java.awt.Dimension(100, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(txtTen, gridBagConstraints);

        jLabel3.setText("Giá trị");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Nội dung ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel4, gridBagConstraints);

        txtNoiDung.setPreferredSize(new java.awt.Dimension(100, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(txtNoiDung, gridBagConstraints);

        lbTrangThai.setText("Trạng thái");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        jPanel2.add(lbTrangThai, gridBagConstraints);

        buttonGroupTrangThai.add(active);
        active.setText("active");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        jPanel2.add(active, gridBagConstraints);

        buttonGroupTrangThai.add(inactive);
        inactive.setText("inactive");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        jPanel2.add(inactive, gridBagConstraints);

        jLabel5.setText("Thời gian");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 3;
        jPanel2.add(jLabel5, gridBagConstraints);

        txtNgayBD.setMinimumSize(new java.awt.Dimension(130, 26));
        txtNgayBD.setPreferredSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        jPanel2.add(txtNgayBD, gridBagConstraints);

        txtNgayKT.setMinimumSize(new java.awt.Dimension(130, 26));
        txtNgayKT.setPreferredSize(new java.awt.Dimension(130, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        jPanel2.add(txtNgayKT, gridBagConstraints);

        jLabel6.setText("Từ ngày");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel8.setText("Đến ngày");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        jPanel2.add(jLabel8, gridBagConstraints);

        spnGiaTri.setPreferredSize(new java.awt.Dimension(100, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(spnGiaTri, gridBagConstraints);

        jLabel9.setText("Sản phẩm áp dụng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel2.add(jLabel9, gridBagConstraints);

        txtMaSP.setPreferredSize(new java.awt.Dimension(100, 26));
        jPanel5.add(txtMaSP);

        btnTimSP.setText("...");
        btnTimSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTimSPMouseClicked(evt);
            }
        });
        jPanel5.add(btnTimSP);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(jPanel5, gridBagConstraints);

        jLabel10.setText("Số lượng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        jPanel2.add(jLabel10, gridBagConstraints);

        spnSoLuong.setPreferredSize(new java.awt.Dimension(100, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(spnSoLuong, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        btnXacNhan.setBackground(new java.awt.Color(102, 187, 106));
        btnXacNhan.setText("Xac nhan");
        btnXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXacNhanMouseClicked(evt);
            }
        });
        jPanel3.add(btnXacNhan);

        btnHuy.setBackground(new java.awt.Color(165, 214, 167));
        btnHuy.setForeground(new java.awt.Color(0, 0, 0));
        btnHuy.setText("Huy");
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyMouseClicked(evt);
            }
        });
        jPanel3.add(btnHuy);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnHuyMouseClicked

    private void btnXacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanMouseClicked
        // TODO add your handling code here:
        xacNhan();
    }//GEN-LAST:event_btnXacNhanMouseClicked

    private void btnTimSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTimSPMouseClicked
        // TODO add your handling code here:
        TimMaSanPhamPopUp popUp = new TimMaSanPhamPopUp(txtMaSP);
        popUp.setVisible(true);
    }//GEN-LAST:event_btnTimSPMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton active;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnTimSP;
    private javax.swing.JButton btnXacNhan;
    protected javax.swing.ButtonGroup buttonGroupTrangThai;
    private javax.swing.JLabel headline;
    private javax.swing.JRadioButton inactive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbTrangThai;
    private javax.swing.JSpinner spnGiaTri;
    private javax.swing.JSpinner spnSoLuong;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtMaSP;
    private com.toedter.calendar.JDateChooser txtNgayBD;
    private com.toedter.calendar.JDateChooser txtNgayKT;
    private javax.swing.JTextField txtNoiDung;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
