/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package do_an_java_new.VIEW.POPUPS;


import do_an_java_new.BLL.TinhThanhBLL;
import do_an_java_new.DTO.NhaCungCapDTO;
import do_an_java_new.DTO.NhanVienDTO;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS-PC
 */
public abstract class NhaCungCapPopUp extends javax.swing.JFrame {

    /**
     * Creates new form NhanVienPopUp
     */
    DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel();
    
    public NhaCungCapPopUp() {
        initComponents();
        
        initComboboxs();
        
    }
    
    public NhaCungCapPopUp(NhaCungCapDTO ncc) {
        initComponents();
        initComboboxs();
        
        txtId.setVisible(false);
        lbID.setVisible(false);
        
        txtTen.setText(ncc.getTenNCC().trim());
        txtTenLH.setText(ncc.getTenLienHe().trim());
        txtSDT.setText(ncc.getSdt());
        cbbTinh.setSelectedItem(ncc.getTinhThanh().trim());
        txtDiaChi.setText(ncc.getDiaChi().trim());
        if (ncc.getTrangThai().equalsIgnoreCase("active"))
            active.setSelected(true);
        else 
            inactive.setSelected(true);
    }
   
    public void setLabel(String labelString) {
        headline.setText(labelString);
    }

    private void initComboboxs() {
        cbbTinh.setModel(comboBoxModel);

        try{
            for (String tinh: TinhThanhBLL.getDanhSachTinh()) {
                comboBoxModel.addElement(tinh);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public abstract void xacNhan();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupTrangThai = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        headline = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtTenLH = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        active = new javax.swing.JRadioButton();
        inactive = new javax.swing.JRadioButton();
        cbbTinh = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        buttonGroupTrangThai.add(active);
        buttonGroupTrangThai.add(inactive);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(430, 550));
        setPreferredSize(new java.awt.Dimension(330, 435));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        headline.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        headline.setForeground(new java.awt.Color(46, 125, 50));
        headline.setText("Thêm nhà cung cấp");
        jPanel1.add(headline);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(232, 245, 233));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel2Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel2.setLayout(jPanel2Layout);

        lbID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbID.setForeground(new java.awt.Color(51, 51, 51));
        lbID.setText("id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(lbID, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Tên liên hệ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("SDT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Tỉnh thành");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel2.add(jLabel9, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Địa chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        jPanel2.add(jLabel10, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Trạng thái");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        jPanel2.add(jLabel13, gridBagConstraints);

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId.setMinimumSize(new java.awt.Dimension(130, 26));
        txtId.setName(""); // NOI18N
        txtId.setPreferredSize(new java.awt.Dimension(130, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        jPanel2.add(txtId, gridBagConstraints);

        txtTenLH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenLH.setMinimumSize(new java.awt.Dimension(130, 26));
        txtTenLH.setName(""); // NOI18N
        txtTenLH.setPreferredSize(new java.awt.Dimension(130, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 9;
        jPanel2.add(txtTenLH, gridBagConstraints);

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSDT.setMinimumSize(new java.awt.Dimension(130, 26));
        txtSDT.setName(""); // NOI18N
        txtSDT.setPreferredSize(new java.awt.Dimension(130, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 9;
        jPanel2.add(txtSDT, gridBagConstraints);

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiaChi.setMinimumSize(new java.awt.Dimension(130, 26));
        txtDiaChi.setName(""); // NOI18N
        txtDiaChi.setPreferredSize(new java.awt.Dimension(130, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 9;
        jPanel2.add(txtDiaChi, gridBagConstraints);

        active.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        active.setForeground(new java.awt.Color(51, 51, 51));
        active.setText("active");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        jPanel2.add(active, gridBagConstraints);

        inactive.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inactive.setForeground(new java.awt.Color(51, 51, 51));
        inactive.setText("inactive");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 12;
        jPanel2.add(inactive, gridBagConstraints);

        cbbTinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 9;
        jPanel2.add(cbbTinh, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel6, gridBagConstraints);

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTen.setMinimumSize(new java.awt.Dimension(130, 26));
        txtTen.setName(""); // NOI18N
        txtTen.setPreferredSize(new java.awt.Dimension(130, 32));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 9;
        jPanel2.add(txtTen, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(232, 245, 233));

        btnXacNhan.setBackground(new java.awt.Color(102, 187, 106));
        btnXacNhan.setText("Xac nhan");
        btnXacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXacNhanMouseClicked(evt);
            }
        });
        jPanel3.add(btnXacNhan);

        btnHuy.setBackground(new java.awt.Color(165, 214, 167));
        btnHuy.setForeground(new java.awt.Color(0, 0, 0));
        btnHuy.setText("Huy");
        btnHuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuyMouseClicked(evt);
            }
        });
        jPanel3.add(btnHuy);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuyMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnHuyMouseClicked

    private void btnXacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanMouseClicked
        // TODO add your handling code here:
        xacNhan();
    }//GEN-LAST:event_btnXacNhanMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JRadioButton active;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnXacNhan;
    protected javax.swing.ButtonGroup buttonGroupTrangThai;
    protected javax.swing.JComboBox<String> cbbTinh;
    private javax.swing.JLabel headline;
    protected javax.swing.JRadioButton inactive;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lbID;
    protected javax.swing.JTextField txtDiaChi;
    protected javax.swing.JTextField txtId;
    protected javax.swing.JTextField txtSDT;
    protected javax.swing.JTextField txtTen;
    protected javax.swing.JTextField txtTenLH;
    // End of variables declaration//GEN-END:variables
}
