/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package do_an_java_new.VIEW.POPUPS.StaffPopUps;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import do_an_java_new.BLL.ChiTietHoaDonBLL;
import do_an_java_new.BLL.HangBLL;
import do_an_java_new.BLL.KhuyenMaiBLL;
import do_an_java_new.DTO.ChiTietHoaDonDTO;
import do_an_java_new.DTO.HangDTO;
import do_an_java_new.DTO.HoaDonDTO;
import do_an_java_new.DTO.KhuyenMaiDTO;
import do_an_java_new.VIEW.WorkSpaces.AdminWorkSpaces.HoaDonPanel;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS-PC
 */
public class BillPopUp extends javax.swing.JFrame {

    /** Creates new form BillPopUp */
    HoaDonDTO hoaDon;
    ArrayList<ChiTietHoaDonDTO> dsCTHD;
    
    public BillPopUp(HoaDonDTO hoadon) {
        initComponents();
        this.hoaDon = hoadon;

        txtMaHD.setText(hoadon.getMaHD());
        txtMaNV.setText(hoadon.getMaNV());
        txtThoiGian.setText(hoadon.getThoiGian().toString());
        txtTongTien.setText(String.format("%d", hoadon.getTongTien()));
        txtGiam.setText(String.format("%d", hoadon.getTienGiam()));
        txtTienTra.setText(String.format("%d", hoadon.getTongTien() - hoadon.getTienGiam()));
        
        renderTable(hoadon.getMaHD());
    }
    
    private void renderTable(String mahd) {
        ArrayList<ChiTietHoaDonDTO> dsCTHD  = null;
        try {
            dsCTHD = ChiTietHoaDonBLL.getCTHD(mahd);
        } catch (SQLException ex) {
            Logger.getLogger(HoaDonPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dsCTHD = dsCTHD;
        
        DefaultTableModel model = (DefaultTableModel) tbChiTietHoaDon.getModel();
        model.setRowCount(0);
        
        try {
            for (ChiTietHoaDonDTO cthd: dsCTHD) {
                HangDTO hang = HangBLL.timHang(cthd.getMaHang());
                model.addRow(new Object[] {
                    cthd.getMaHang(),
                    hang.getTenSP(),
                    cthd.getSoLuong(),
                    cthd.getDonGia()
                });
            }            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtThoiGian = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnPDF = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbChiTietHoaDon = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTienTra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGiam = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(536, 500));

        jPanel4.setToolTipText("");
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã hoá đơn");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        txtMaHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaHD.setPreferredSize(new java.awt.Dimension(130, 30));
        txtMaHD.setRequestFocusEnabled(false);
        jPanel5.add(txtMaHD, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã nhân viên");
        jPanel6.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaNV.setPreferredSize(new java.awt.Dimension(130, 30));
        txtMaNV.setRequestFocusEnabled(false);
        jPanel6.add(txtMaNV, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Thời gian");
        jPanel7.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        txtThoiGian.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtThoiGian.setPreferredSize(new java.awt.Dimension(130, 30));
        txtThoiGian.setRequestFocusEnabled(false);
        jPanel7.add(txtThoiGian, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel7);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jButton1.setBackground(new java.awt.Color(0, 173, 59));
        jButton1.setText("Hoàn tất");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);

        btnPDF.setBackground(new java.awt.Color(255, 153, 153));
        btnPDF.setText("Xuất pdf");
        btnPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPDFMouseClicked(evt);
            }
        });
        jPanel1.add(btnPDF);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(232, 245, 233));

        tbChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hàng", "Tên sản phẩm", "Số lượng", "Đơn giá"
            }
        ));
        jScrollPane2.setViewportView(tbChiTietHoaDon);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tổng tiền");
        jPanel8.add(jLabel1, new java.awt.GridBagConstraints());

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTongTien.setPreferredSize(new java.awt.Dimension(130, 30));
        jPanel8.add(txtTongTien, new java.awt.GridBagConstraints());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tiền trả");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel8.add(jLabel5, gridBagConstraints);

        txtTienTra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTienTra.setPreferredSize(new java.awt.Dimension(130, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel8.add(txtTienTra, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Giảm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel8.add(jLabel6, gridBagConstraints);

        txtGiam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGiam.setPreferredSize(new java.awt.Dimension(130, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel8.add(txtGiam, gridBagConstraints);

        jPanel3.add(jPanel8);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPDFMouseClicked
        // TODO add your handling code here:
        try {
            // Chọn nơi lưu file PDF
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Lưu file PDF");
            int userSelection = fileChooser.showSaveDialog(this);

            if (userSelection == JFileChooser.APPROVE_OPTION) {
                String filePath = fileChooser.getSelectedFile().getAbsolutePath() + ".pdf";

                // Tạo nội dung PDF
                Document document = new Document();
                PdfWriter.getInstance(document, new FileOutputStream(filePath));
                document.open();

                // Font hỗ trợ tiếng Việt
                BaseFont baseFont = BaseFont.createFont("lib/arial.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
                Font titleFont = new Font(baseFont, 16, Font.BOLD);
                Font normalFont = new Font(baseFont, 12, Font.NORMAL);
                Font totalFont = new Font(baseFont, 12, Font.BOLD);

                // Tiêu đề hóa đơn
                Paragraph title = new Paragraph("CỬA HÀNG THỰC PHẨM\nHóa Đơn Bán Hàng", titleFont);
                title.setAlignment(Element.ALIGN_CENTER);
                document.add(title);

                document.add(Chunk.NEWLINE);

                // Thông tin hóa đơn
                document.add(new Paragraph("Mã hóa đơn: " + hoaDon.getMaHD(), normalFont));
                document.add(new Paragraph("Ngày lập: " + hoaDon.getThoiGian().toString(), normalFont));
                document.add(new Paragraph("Nhân viên: " + hoaDon.getMaNV(), normalFont));
                document.add(new Paragraph("Khách hàng: " + hoaDon.getMaKH(), normalFont));
                document.add(new Paragraph("Khuyến mãi: " + hoaDon.getMaKM(), normalFont));

                document.add(Chunk.NEWLINE);

                // Bảng danh sách sản phẩm
                PdfPTable tablePDF = new PdfPTable(5);
                Paragraph productTitle = new Paragraph("\nDANH SÁCH SẢN PHẨM MUA", titleFont);
                productTitle.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
                document.add(productTitle);
                tablePDF.setWidthPercentage(100);
                tablePDF.setSpacingBefore(10f);
                tablePDF.setSpacingAfter(10f);

                // Tiêu đề cột
                String[] headers = {"Tên sản phẩm", "Số lượng", "Đơn giá", "Giảm giá", "Thành tiền"};
                for (String header : headers) {
                    PdfPCell cell = new PdfPCell(new Phrase(header, normalFont));
                    cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    tablePDF.addCell(cell);
                }

                // Dữ liệu chi tiết hóa đơn
                for (ChiTietHoaDonDTO cthd : dsCTHD) {
                    HangDTO hang = HangBLL.timHang(cthd.getMaHang());
                    KhuyenMaiDTO khuyenMai = KhuyenMaiBLL.timKhuyenMai(hoaDon.getMaKM()); // Lấy thông tin khuyến mãi

                    int giamGia = khuyenMai != null ? khuyenMai.getGiaTri() : 0;
                    double thanhTien = cthd.getSoLuong() * cthd.getDonGia() * (1 - giamGia / 100);

                    tablePDF.addCell(new PdfPCell(new Phrase(hang.getTenSP(), normalFont)));
                    tablePDF.addCell(new PdfPCell(new Phrase(String.valueOf(cthd.getSoLuong()), normalFont)));
                    tablePDF.addCell(new PdfPCell(new Phrase(String.format("%,.0f VNĐ", (double) cthd.getDonGia()), normalFont)));
                    tablePDF.addCell(new PdfPCell(new Phrase(String.format("%d%%", giamGia), normalFont)));
                    tablePDF.addCell(new PdfPCell(new Phrase(String.format("%,.0f VNĐ", thanhTien), normalFont)));
                }

                document.add(tablePDF);

                // Tổng tiền
                Paragraph total = new Paragraph("Tổng tiền: " +hoaDon.getTongTien() + " VNĐ", totalFont);
                total.add(new Chunk("\nTiền giảm: "+hoaDon.getTienGiam()+" VNĐ", totalFont));
                int tienTra =  hoaDon.getTongTien()-hoaDon.getTienGiam();
                total.add(new Chunk("\nTổng tiền phải trả: "+tienTra+" VNĐ", totalFont));
                total.setAlignment(Element.ALIGN_RIGHT);
                document.add(total);

                document.add(Chunk.NEWLINE);

                // Lời cảm ơn
                Paragraph thankYou = new Paragraph("XIN CẢM ƠN QUÝ KHÁCH!", titleFont);
                thankYou.setAlignment(Element.ALIGN_CENTER);
                document.add(thankYou);

                // Đóng tài liệu
                document.close();

                JOptionPane.showMessageDialog(this, "Xuất file PDF thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi tạo PDF: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPDFMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbChiTietHoaDon;
    private javax.swing.JTextField txtGiam;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtThoiGian;
    private javax.swing.JTextField txtTienTra;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

}
