/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package do_an_java_new.VIEW.WorkSpaces.AdminWorkSpaces;

/**
 *
 * @author pducn
 */
public class ThongKePanel extends javax.swing.JPanel {

    /**
     * Creates new form NhanVienPanel
     */
    public ThongKePanel() {
        initComponents();
        sanpham.add(new ThongKeSanPhamPanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        sanpham = new javax.swing.JPanel();
        nhanvien = new javax.swing.JPanel();
        khachhang = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(0, 0));
        setMinimumSize(new java.awt.Dimension(1080, 800));
        setPreferredSize(new java.awt.Dimension(1080, 800));
        setLayout(new java.awt.BorderLayout());

        sanpham.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("Sản phẩm", sanpham);

        nhanvien.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("Nhân viên", nhanvien);

        khachhang.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("Khách hàng", khachhang);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel khachhang;
    private javax.swing.JPanel nhanvien;
    private javax.swing.JPanel sanpham;
    // End of variables declaration//GEN-END:variables
}
