/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package do_an_java_new.VIEW.WorkSpaces.AdminWorkSpaces;
import do_an_java_new.BLL.KhachHangBLL;
import do_an_java_new.BLL.NhanVienBLL;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author ASUS-PC
 */
public class ThongKeKhachHangPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeSanPhamPanel
     */
    private DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    
    public ThongKeKhachHangPanel() {
        initComponents();
        
        renderCountType(2);
        Date 
                begin = Date.valueOf(String.format("%d-1-1", txtYear.getValue())),
                end = Date.valueOf(String.format("%d-12-31", txtYear.getValue()));

        renderTable(begin, end);
        renderChart();
    }
    
    private void renderCountType(int option) {
        switch (option) {
            case 0:
                beginDate.setVisible(true);
                endDate.setVisible(true);
                month.setVisible(false);
                year.setVisible(false);
                break;
            case 1:
                month.setVisible(true);
                year.setVisible(true);
                beginDate.setVisible(false);
                endDate.setVisible(false);
                break;
            case 2:
                month.setVisible(false);
                year.setVisible(true);
                beginDate.setVisible(false);
                endDate.setVisible(false);     
                break;
            default:
                throw new AssertionError();
        }
    }
    
    private void renderTable(Date begin, Date end) {
        DefaultTableModel model = (DefaultTableModel) tbCount.getModel();
        model.setRowCount(0);
        dataset.clear();
        
        try {
            for (Object[] thongKe: KhachHangBLL.thongKeKhachHang(begin, end)) {
                model.addRow(thongKe);
                dataset.addValue((int)thongKe[4], "Lợi nhuận", (Comparable) thongKe[0]);
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void renderChart() {
        JFreeChart chart = ChartFactory.createBarChart(
            "Thống kê khách hàng",
            "Khách hàng",
            "Lợi nhuận",
            dataset,     
            PlotOrientation.HORIZONTAL, true, true, false
        );
        
        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setMaximumBarWidth(0.2);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        chartScrollPane.setViewportView(chartPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cbbCountType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        beginDate = new javax.swing.JPanel();
        lbBeginDate = new javax.swing.JLabel();
        txtBeginDate = new com.toedter.calendar.JDateChooser();
        endDate = new javax.swing.JPanel();
        lbEndDate = new javax.swing.JLabel();
        txtEndDate = new com.toedter.calendar.JDateChooser();
        year = new javax.swing.JPanel();
        lbYear = new javax.swing.JLabel();
        txtYear = new com.toedter.calendar.JYearChooser();
        month = new javax.swing.JPanel();
        lbMonth = new javax.swing.JLabel();
        txtMonth = new com.toedter.calendar.JMonthChooser();
        jPanel3 = new javax.swing.JPanel();
        btnCount = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCount = new javax.swing.JTable();
        chartScrollPane = new javax.swing.JScrollPane();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 173, 59));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(0, 173, 59));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        cbbCountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày→Ngày", "Theo tháng", "Theo năm" }));
        cbbCountType.setSelectedIndex(2);
        cbbCountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbCountTypeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel5.add(cbbCountType, gridBagConstraints);

        jLabel1.setText("Kiểu thống kê");
        jPanel5.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel4.setBackground(new java.awt.Color(0, 173, 59));
        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        jPanel4Layout.rowHeights = new int[] {0, 20, 0, 20, 0};
        jPanel4.setLayout(jPanel4Layout);

        lbBeginDate.setText("Từ ngày");
        beginDate.add(lbBeginDate);

        txtBeginDate.setDate(Date.valueOf(LocalDate.now()));
        txtBeginDate.setPreferredSize(new java.awt.Dimension(130, 26));
        beginDate.add(txtBeginDate);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel4.add(beginDate, gridBagConstraints);

        lbEndDate.setText("Đến ngày");
        endDate.add(lbEndDate);

        txtEndDate.setDate(Date.valueOf(LocalDate.now()));
        txtEndDate.setPreferredSize(new java.awt.Dimension(130, 26));
        endDate.add(txtEndDate);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel4.add(endDate, gridBagConstraints);

        lbYear.setText("Chọn năm");
        year.add(lbYear);

        txtYear.setPreferredSize(new java.awt.Dimension(130, 30));
        year.add(txtYear);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel4.add(year, gridBagConstraints);

        lbMonth.setText("Chọn Tháng");
        month.add(lbMonth);

        txtMonth.setPreferredSize(new java.awt.Dimension(130, 30));
        month.add(txtMonth);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel4.add(month, gridBagConstraints);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(0, 173, 59));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        btnCount.setText("Thống kê");
        btnCount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCountMouseClicked(evt);
            }
        });
        jPanel3.add(btnCount, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel3, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tbCount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã", "Họ", "Tên", "Số lượng sản phẩm đã mua", "Tổng số tiền"
            }
        ));
        jScrollPane1.setViewportView(tbCount);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        chartScrollPane.setPreferredSize(null);
        add(chartScrollPane, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void cbbCountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbCountTypeActionPerformed
        // TODO add your handling code here:
        int selectedIndex = cbbCountType.getSelectedIndex();
        renderCountType(selectedIndex);
    }//GEN-LAST:event_cbbCountTypeActionPerformed

    private void btnCountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCountMouseClicked
        // TODO add your handling code here:
        Date begin = null, end = null;
        int daysOfMonth;
        switch(cbbCountType.getSelectedIndex()) {
            case 0:
                begin = new Date(txtBeginDate.getDate().getTime());
                end = new Date(txtEndDate.getDate().getTime());
                break;
            case 1:
                begin = Date.valueOf(String.format("%d-%d-1", txtYear.getValue(), txtMonth.getMonth() + 1));
                daysOfMonth = LocalDate.of(txtYear.getValue(), txtMonth.getMonth(), 1).lengthOfMonth() - 1;
                end = Date.valueOf(String.format("%d-%d-%d", txtYear.getValue(), txtMonth.getMonth() + 1, daysOfMonth));
                break;
            case 2:
                begin = Date.valueOf(String.format("%d-1-1", txtYear.getValue()));
                end = Date.valueOf(String.format("%d-12-31", txtYear.getValue()));
                break;
            default:
                break;
        }
        
        renderTable(begin, end);
    }//GEN-LAST:event_btnCountMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel beginDate;
    private javax.swing.JButton btnCount;
    private javax.swing.JComboBox<String> cbbCountType;
    private javax.swing.JScrollPane chartScrollPane;
    private javax.swing.JPanel endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBeginDate;
    private javax.swing.JLabel lbEndDate;
    private javax.swing.JLabel lbMonth;
    private javax.swing.JLabel lbYear;
    private javax.swing.JPanel month;
    private javax.swing.JTable tbCount;
    private com.toedter.calendar.JDateChooser txtBeginDate;
    private com.toedter.calendar.JDateChooser txtEndDate;
    private com.toedter.calendar.JMonthChooser txtMonth;
    private com.toedter.calendar.JYearChooser txtYear;
    private javax.swing.JPanel year;
    // End of variables declaration//GEN-END:variables
}
