/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package do_an_java_new.VIEW;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import do_an_java_new.BLL.NhanVienBLL;
import do_an_java_new.DTO.NhanVienDTO;
import do_an_java_new.Login;
import do_an_java_new.VIEW.WorkSpaces.TrangChuPanel;
import do_an_java_new.VIEW.WorkSpaces.StaffWorkSpaces.LapHoaDonPanel;
import do_an_java_new.VIEW.WorkSpaces.StaffWorkSpaces.NhapHangPanel;
import do_an_java_new.VIEW.WorkSpaces.StaffWorkSpaces.ThemKhachhangPanel;
import do_an_java_new.VIEW.WorkSpaces.StaffWorkSpaces.ThongTinNhanVien;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author pducn
 */
public class StaffFrame extends javax.swing.JFrame {
    private String currentPanel;
    private CardLayout cardLayout;
    private NhanVienDTO nhanVien;
    //tuong tu
    /**
     * Creates new form MainFrame
     */
    public String getCurrentPanel() {
        return currentPanel;
    }
    
    public StaffFrame() throws Exception {
        initComponents();
        
        renderCenterPanel();
        cardLayout = (CardLayout) pnCenter.getLayout();
    }
    
    public StaffFrame(NhanVienDTO nhanVien) throws Exception {
        initComponents();
        this.nhanVien = nhanVien;
        
        jLabel4.setText(String.format("<html>%s<br><small>STAFF</small></html> ", nhanVien.getFullName()));
        
        renderCenterPanel();
        cardLayout = (CardLayout) pnCenter.getLayout();
    }    
    
    private void renderCenterPanel() {
        pnCenter.add(new TrangChuPanel(),"TRANGCHU");
        pnCenter.add(new LapHoaDonPanel(nhanVien.getMaNV()), "HOADON");
        pnCenter.add(new NhapHangPanel(nhanVien.getMaNV()), "NHAPHANG");
        pnCenter.add(new ThemKhachhangPanel(), "KHACHHANG");
        pnCenter.add(new ThongTinNhanVien(nhanVien), "THONGTIN");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnLeft = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        SignOut = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TrangChu1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TrangChu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Quan_ly_hoa_don = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Quan_ly_nhap_hang = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Quan_ly_khach_hang = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnCenter = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        pnLeft.setBackground(new java.awt.Color(6, 117, 60));
        pnLeft.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 51), 4, true));
        pnLeft.setMaximumSize(new java.awt.Dimension(200, 400));
        pnLeft.setMinimumSize(new java.awt.Dimension(200, 400));
        pnLeft.setPreferredSize(new java.awt.Dimension(200, 0));
        pnLeft.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/do_an_java_new/Resources/desktop48.png"))); // NOI18N
        jLabel4.setText("<html>SIÊU QUẢN LÝ<br><small>ADMIN</small></html> ");
        jLabel4.setToolTipText("");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel4.setVerifyInputWhenFocusTarget(false);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        pnLeft.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        SignOut.setBackground(new java.awt.Color(255, 153, 255));
        SignOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)));
        SignOut.setForeground(new java.awt.Color(255, 255, 255));
        SignOut.setOpaque(true);
        SignOut.setPreferredSize(new java.awt.Dimension(199, 40));
        SignOut.setLayout(new java.awt.GridLayout(1, 3, 0, 100));

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Đăng Xuất");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        SignOut.add(jLabel36);

        pnLeft.add(SignOut, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        TrangChu1.setBackground(new java.awt.Color(153, 255, 153));
        TrangChu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)));
        TrangChu1.setForeground(new java.awt.Color(255, 255, 255));
        TrangChu1.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        TrangChu1.setOpaque(true);
        TrangChu1.setPreferredSize(new java.awt.Dimension(195, 40));
        TrangChu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrangChu1MouseClicked(evt);
            }
        });
        TrangChu1.setLayout(new java.awt.GridBagLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/do_an_java_new/Resources/Info - Copy.png"))); // NOI18N
        jLabel12.setFocusable(false);
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        TrangChu1.add(jLabel12, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Thông tin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        TrangChu1.add(jLabel6, gridBagConstraints);

        jPanel1.add(TrangChu1);

        TrangChu.setBackground(new java.awt.Color(153, 255, 153));
        TrangChu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)));
        TrangChu.setForeground(new java.awt.Color(255, 255, 255));
        TrangChu.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        TrangChu.setOpaque(true);
        TrangChu.setPreferredSize(new java.awt.Dimension(195, 40));
        TrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrangChuMouseClicked(evt);
            }
        });
        TrangChu.setLayout(new java.awt.GridBagLayout());

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/do_an_java_new/Resources/icons8-home-16.png"))); // NOI18N
        jLabel8.setFocusable(false);
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        TrangChu.add(jLabel8, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText(" Trang chủ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        TrangChu.add(jLabel5, gridBagConstraints);

        jPanel1.add(TrangChu);

        Quan_ly_hoa_don.setBackground(new java.awt.Color(153, 255, 153));
        Quan_ly_hoa_don.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)));
        Quan_ly_hoa_don.setForeground(new java.awt.Color(255, 255, 255));
        Quan_ly_hoa_don.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        Quan_ly_hoa_don.setOpaque(true);
        Quan_ly_hoa_don.setPreferredSize(new java.awt.Dimension(195, 40));
        Quan_ly_hoa_don.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Quan_ly_hoa_donMouseClicked(evt);
            }
        });
        Quan_ly_hoa_don.setLayout(new java.awt.GridBagLayout());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/do_an_java_new/Resources/icons8-bill-16.png"))); // NOI18N
        jLabel23.setFocusable(false);
        jLabel23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 3, 0, 0);
        Quan_ly_hoa_don.add(jLabel23, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Hoá Đơn");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.8;
        Quan_ly_hoa_don.add(jLabel10, gridBagConstraints);

        jPanel1.add(Quan_ly_hoa_don);

        Quan_ly_nhap_hang.setBackground(new java.awt.Color(153, 255, 153));
        Quan_ly_nhap_hang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)));
        Quan_ly_nhap_hang.setForeground(new java.awt.Color(255, 255, 255));
        Quan_ly_nhap_hang.setMaximumSize(new java.awt.Dimension(2147483647, 50));
        Quan_ly_nhap_hang.setOpaque(true);
        Quan_ly_nhap_hang.setPreferredSize(new java.awt.Dimension(195, 40));
        Quan_ly_nhap_hang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Quan_ly_nhap_hangMouseClicked(evt);
            }
        });
        Quan_ly_nhap_hang.setLayout(new java.awt.GridBagLayout());

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/do_an_java_new/Resources/icons8-list-view-16.png"))); // NOI18N
        jLabel24.setFocusable(false);
        jLabel24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 3, 0, 0);
        Quan_ly_nhap_hang.add(jLabel24, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Nhập hàng");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.8;
        Quan_ly_nhap_hang.add(jLabel11, gridBagConstraints);

        jPanel1.add(Quan_ly_nhap_hang);

        Quan_ly_khach_hang.setBackground(new java.awt.Color(153, 255, 153));
        Quan_ly_khach_hang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 153)));
        Quan_ly_khach_hang.setForeground(new java.awt.Color(255, 255, 255));
        Quan_ly_khach_hang.setMaximumSize(new java.awt.Dimension(2147483647, 40));
        Quan_ly_khach_hang.setOpaque(true);
        Quan_ly_khach_hang.setPreferredSize(new java.awt.Dimension(195, 40));
        Quan_ly_khach_hang.setLayout(new java.awt.GridBagLayout());

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/do_an_java_new/Resources/icons8-customer-16.png"))); // NOI18N
        jLabel22.setFocusable(false);
        jLabel22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 3, 0, 0);
        Quan_ly_khach_hang.add(jLabel22, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Thêm khách Hàng");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.8;
        Quan_ly_khach_hang.add(jLabel9, gridBagConstraints);

        jPanel1.add(Quan_ly_khach_hang);

        pnLeft.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnLeft, java.awt.BorderLayout.WEST);

        pnCenter.setBackground(new java.awt.Color(204, 255, 204));
        pnCenter.setMaximumSize(new java.awt.Dimension(1080, 800));
        pnCenter.setMinimumSize(new java.awt.Dimension(1080, 800));
        pnCenter.setPreferredSize(new java.awt.Dimension(1080, 800));
        pnCenter.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnCenter, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Chắc chắn muốn đăng xuất?", "Đăng xuất", JOptionPane.YES_NO_OPTION) ;
        if (confirm != JOptionPane.YES_OPTION)
            return ;
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jLabel36MouseClicked

    private void TrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrangChuMouseClicked
        // TODO add your handling code here:
        cardLayout.show(pnCenter, "TRANGCHU");
        
    }//GEN-LAST:event_TrangChuMouseClicked

    private void Quan_ly_hoa_donMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Quan_ly_hoa_donMouseClicked
        // TODO add your handling code here:
        cardLayout.show(pnCenter, "HOADON");
    }//GEN-LAST:event_Quan_ly_hoa_donMouseClicked

    private void Quan_ly_nhap_hangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Quan_ly_nhap_hangMouseClicked
        // TODO add your handling code here:
        cardLayout.show(pnCenter, "NHAPHANG");
    }//GEN-LAST:event_Quan_ly_nhap_hangMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        cardLayout.show(pnCenter, "KHACHHANG");
    }//GEN-LAST:event_jLabel9MouseClicked

    private void TrangChu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrangChu1MouseClicked
        // TODO add your handling code here:
        cardLayout.show(pnCenter, "THONGTIN");
    }//GEN-LAST:event_TrangChu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new StaffFrame(NhanVienBLL.getNhanVien("dutran")).setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(StaffFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Quan_ly_hoa_don;
    private javax.swing.JPanel Quan_ly_khach_hang;
    private javax.swing.JPanel Quan_ly_nhap_hang;
    private javax.swing.JPanel SignOut;
    private javax.swing.JPanel TrangChu;
    private javax.swing.JPanel TrangChu1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnLeft;
    // End of variables declaration//GEN-END:variables
}
